# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

.include "macros.inc"

.data

# (0x7E6850 - ?)

.align 2, 0x00
glabel gTextureSmallFont0
.incbin "textures/standalone/small_letter_0.ia16.mio0"
glabel gTextureSmallFont0_end

.align 2, 0x00
glabel gTextureSmallFont1
.incbin "textures/standalone/small_letter_1.ia16.mio0"
glabel gTextureSmallFont1_end

.align 2, 0x00
glabel gTextureSmallFont2
.incbin "textures/standalone/small_letter_2.ia16.mio0"
glabel gTextureSmallFont2_end

.align 2, 0x00
glabel gTextureSmallFont3
.incbin "textures/standalone/small_letter_3.ia16.mio0"
glabel gTextureSmallFont3_end

.align 2, 0x00
glabel gTextureSmallFont4
.incbin "textures/standalone/small_letter_4.ia16.mio0"
glabel gTextureSmallFont4_end

.align 2, 0x00
glabel gTextureSmallFont5
.incbin "textures/standalone/small_letter_5.ia16.mio0"
glabel gTextureSmallFont5_end

.align 2, 0x00
glabel gTextureSmallFont6
.incbin "textures/standalone/small_letter_6.ia16.mio0"
glabel gTextureSmallFont6_end

.align 2, 0x00
glabel gTextureSmallFont7
.incbin "textures/standalone/small_letter_7.ia16.mio0"
glabel gTextureSmallFont7_end

.align 2, 0x00
glabel gTextureSmallFont8
.incbin "textures/standalone/small_letter_8.ia16.mio0"
glabel gTextureSmallFont8_end

.align 2, 0x00
glabel gTextureSmallFont9
.incbin "textures/standalone/small_letter_9.ia16.mio0"
glabel gTextureSmallFont9_end

.align 2, 0x00
glabel gTextureN64ControllerPakDataSelect
.incbin "textures/standalone/n64_controller_pak_data_select.ia16.mio0"
glabel gTextureN64ControllerPakDataSelect_end

.align 2, 0x00
glabel gTextureEraseDataRecordConfirmation
.incbin "textures/standalone/erase_data_record_confirmation.ia16.mio0"
glabel gTextureEraseDataRecordConfirmation_end

.align 2, 0x00
glabel gTextureRecordNotErased
.incbin "textures/standalone/record_not_erased.ia16.mio0"
glabel gTextureRecordNotErased_end

.align 2, 0x00
glabel gTexturePlaceN64ControllerPakIntoController1
.incbin "textures/standalone/place_n64_controller_pak_into_controller_1.ia16.mio0"
glabel gTexturePlaceN64ControllerPakIntoController1_end

.align 2, 0x00
glabel gTexturePleaseReinsertOriginalN64ControllerPak
.incbin "textures/standalone/please_reinsert_original_n64_controller_pak.ia16.mio0"
glabel gTexturePleaseReinsertOriginalN64ControllerPak_end

.align 2, 0x00
glabel gTextureErasingSelectedRecord
.incbin "textures/standalone/erasing_selected_record.ia16.mio0"
glabel gTextureErasingSelectedRecord_end

.align 2, 0x00
glabel gTextureSelectRecord
.incbin "textures/standalone/select_record.ia16.mio0"
glabel gTextureSelectRecord_end

.align 2, 0x00
glabel gTextureTextEnd
.incbin "textures/standalone/text_end.ia16.mio0"
glabel gTextureTextEnd_end

.align 2, 0x00
glabel gTextureTableOfContents
.incbin "textures/standalone/table_of_contents.ia16.mio0"
glabel gTextureTableOfContents_end

.align 2, 0x00
glabel gTextureTextHash
.incbin "textures/standalone/text_hash.ia16.mio0"
glabel gTextureTextHash_end

.align 2, 0x00
glabel gTextureTextGameData
.incbin "textures/standalone/text_game_data.ia16.mio0"
glabel gTextureTextGameData_end

.align 2, 0x00
glabel gTextureTextPages
.incbin "textures/standalone/text_pages.ia16.mio0"
glabel gTextureTextPages_end

.align 2, 0x00
glabel gTextureTextPagesFree
.incbin "textures/standalone/text_pages_free.ia16.mio0"
glabel gTextureTextPagesFree_end

.align 2, 0x00
glabel gTextureTextErase
.incbin "textures/standalone/text_erase.ia16.mio0"
glabel gTextureTextErase_end

.align 2, 0x00
glabel gTextureTextQuit
.incbin "textures/standalone/text_quit.ia16.mio0"
glabel gTextureTextQuit_end

.align 2, 0x00
glabel gTexture7ED058
.incbin "textures/standalone/texture_7ED058.ia16.mio0"
glabel gTexture7ED058_end

.align 2, 0x00
glabel gTexture7ED290
.incbin "textures/standalone/texture_7ED290.ia16.mio0"
glabel gTexture7ED290_end

.align 2, 0x00
glabel gTexture7ED50C
.incbin "textures/standalone/texture_7ED50C.ia16.mio0"
glabel gTexture7ED50C_end

.align 2, 0x00
glabel gTexture7ED6A4
.incbin "textures/standalone/texture_7ED6A4.ia16.mio0"
glabel gTexture7ED6A4_end

.align 2, 0x00
glabel gTextureTinyFont0
.incbin "textures/standalone/tiny_font_0.ia16.mio0"
glabel gTextureTinyFont0_end

.align 2, 0x00
glabel gTextureTinyFont1
.incbin "textures/standalone/tiny_font_1.ia16.mio0"
glabel gTextureTinyFont1_end

.align 2, 0x00
glabel gTextureTinyFont2
.incbin "textures/standalone/tiny_font_2.ia16.mio0"
glabel gTextureTinyFont2_end

.align 2, 0x00
glabel gTextureTinyFont3
.incbin "textures/standalone/tiny_font_3.ia16.mio0"
glabel gTextureTinyFont3_end

.align 2, 0x00
glabel gTextureTinyFont4
.incbin "textures/standalone/tiny_font_4.ia16.mio0"
glabel gTextureTinyFont4_end

.align 2, 0x00
glabel gTextureTinyFont5
.incbin "textures/standalone/tiny_font_5.ia16.mio0"
glabel gTextureTinyFont5_end

.align 2, 0x00
glabel gTextureTinyFont6
.incbin "textures/standalone/tiny_font_6.ia16.mio0"
glabel gTextureTinyFont6_end

.align 2, 0x00
glabel gTextureTinyFont7
.incbin "textures/standalone/tiny_font_7.ia16.mio0"
glabel gTextureTinyFont7_end

.align 2, 0x00
glabel gTextureTinyFont8
.incbin "textures/standalone/tiny_font_8.ia16.mio0"
glabel gTextureTinyFont8_end

.align 2, 0x00
glabel gTextureTinyFont9
.incbin "textures/standalone/tiny_font_9.ia16.mio0"
glabel gTextureTinyFont9_end

.align 2, 0x00
glabel gTextureTinyFontA
.incbin "textures/standalone/tiny_font_A.ia16.mio0"
glabel gTextureTinyFontA_end

.align 2, 0x00
glabel gTextureTinyFontB
.incbin "textures/standalone/tiny_font_B.ia16.mio0"
glabel gTextureTinyFontB_end

.align 2, 0x00
glabel gTextureTinyFontC
.incbin "textures/standalone/tiny_font_C.ia16.mio0"
glabel gTextureTinyFontC_end

.align 2, 0x00
glabel gTextureTinyFontD
.incbin "textures/standalone/tiny_font_D.ia16.mio0"
glabel gTextureTinyFontD_end

.align 2, 0x00
glabel gTextureTinyFontE
.incbin "textures/standalone/tiny_font_E.ia16.mio0"
glabel gTextureTinyFontE_end

.align 2, 0x00
glabel gTextureTinyFontF
.incbin "textures/standalone/tiny_font_F.ia16.mio0"
glabel gTextureTinyFontF_end

.align 2, 0x00
glabel gTextureTinyFontG
.incbin "textures/standalone/tiny_font_G.ia16.mio0"
glabel gTextureTinyFontG_end

.align 2, 0x00
glabel gTextureTinyFontH
.incbin "textures/standalone/tiny_font_H.ia16.mio0"
glabel gTextureTinyFontH_end

.align 2, 0x00
glabel gTextureTinyFontI
.incbin "textures/standalone/tiny_font_I.ia16.mio0"
glabel gTextureTinyFontI_end

.align 2, 0x00
glabel gTextureTinyFontJ
.incbin "textures/standalone/tiny_font_J.ia16.mio0"
glabel gTextureTinyFontJ_end

.align 2, 0x00
glabel gTextureTinyFontK
.incbin "textures/standalone/tiny_font_K.ia16.mio0"
glabel gTextureTinyFontK_end

.align 2, 0x00
glabel gTextureTinyFontL
.incbin "textures/standalone/tiny_font_L.ia16.mio0"
glabel gTextureTinyFontL_end

.align 2, 0x00
glabel gTextureTinyFontM
.incbin "textures/standalone/tiny_font_M.ia16.mio0"
glabel gTextureTinyFontM_end

.align 2, 0x00
glabel gTextureTinyFontN
.incbin "textures/standalone/tiny_font_N.ia16.mio0"
glabel gTextureTinyFontN_end

.align 2, 0x00
glabel gTextureTinyFontO
.incbin "textures/standalone/tiny_font_O.ia16.mio0"
glabel gTextureTinyFontO_end

.align 2, 0x00
glabel gTextureTinyFontP
.incbin "textures/standalone/tiny_font_P.ia16.mio0"
glabel gTextureTinyFontP_end

.align 2, 0x00
glabel gTextureTinyFontQ
.incbin "textures/standalone/tiny_font_Q.ia16.mio0"
glabel gTextureTinyFontQ_end

.align 2, 0x00
glabel gTextureTinyFontR
.incbin "textures/standalone/tiny_font_R.ia16.mio0"
glabel gTextureTinyFontR_end

.align 2, 0x00
glabel gTextureTinyFontS
.incbin "textures/standalone/tiny_font_S.ia16.mio0"
glabel gTextureTinyFontS_end

.align 2, 0x00
glabel gTextureTinyFontT
.incbin "textures/standalone/tiny_font_T.ia16.mio0"
glabel gTextureTinyFontT_end

.align 2, 0x00
glabel gTextureTinyFontU
.incbin "textures/standalone/tiny_font_U.ia16.mio0"
glabel gTextureTinyFontU_end

.align 2, 0x00
glabel gTextureTinyFontV
.incbin "textures/standalone/tiny_font_V.ia16.mio0"
glabel gTextureTinyFontV_end

.align 2, 0x00
glabel gTextureTinyFontW
.incbin "textures/standalone/tiny_font_W.ia16.mio0"
glabel gTextureTinyFontW_end

.align 2, 0x00
glabel gTextureTinyFontX
.incbin "textures/standalone/tiny_font_X.ia16.mio0"
glabel gTextureTinyFontX_end

.align 2, 0x00
glabel gTextureTinyFontY
.incbin "textures/standalone/tiny_font_Y.ia16.mio0"
glabel gTextureTinyFontY_end

.align 2, 0x00
glabel gTextureTinyFontZ
.incbin "textures/standalone/tiny_font_Z.ia16.mio0"
glabel gTextureTinyFontZ_end

.align 2, 0x00
glabel gTextureTinyFontExclamationMark
.incbin "textures/standalone/tiny_font_exclamation_mark.ia16.mio0"
glabel gTextureTinyFontExclamationMark_end

.align 2, 0x00
glabel gTextureTinyFontDoubleQuote
.incbin "textures/standalone/tiny_font_double_quote.ia16.mio0"
glabel gTextureTinyFontDoubleQuote_end

.align 2, 0x00
glabel gTextureTinyFontHash
.incbin "textures/standalone/tiny_font_hash.ia16.mio0"
glabel gTextureTinyFontHash_end

.align 2, 0x00
glabel gTextureTinyFontSingleQuote
.incbin "textures/standalone/tiny_font_single_quote.ia16.mio0"
glabel gTextureTinyFontSingleQuote_end

.align 2, 0x00
glabel gTextureTinyFontAsterisk
.incbin "textures/standalone/tiny_font_asterisk.ia16.mio0"
glabel gTextureTinyFontAsterisk_end

.align 2, 0x00
glabel gTextureTinyFontPlus
.incbin "textures/standalone/tiny_font_plus.ia16.mio0"
glabel gTextureTinyFontPlus_end

.align 2, 0x00
glabel gTexture7EEB18
.incbin "textures/standalone/texture_7EEB18.ia16.mio0"
glabel gTexture7EEB18_end

.align 2, 0x00
glabel gTextureTinyFontMinus
.incbin "textures/standalone/tiny_font_minus.ia16.mio0"
glabel gTextureTinyFontMinus_end

.align 2, 0x00
glabel gTextureTinyFontComma
.incbin "textures/standalone/tiny_font_dot.ia16.mio0"
glabel gTextureTinyFontComma_end

.align 2, 0x00
glabel gTextureTinyFontForwardSlash
.incbin "textures/standalone/tiny_font_forward_slash.ia16.mio0"
glabel gTextureTinyFontForwardSlash_end

.align 2, 0x00
glabel gTextureTinyFontColon
.incbin "textures/standalone/tiny_font_colon.ia16.mio0"
glabel gTextureTinyFontColon_end

.align 2, 0x00
glabel gTexture7EEC34
.incbin "textures/standalone/texture_7EEC34.ia16.mio0"
glabel gTexture7EEC34_end

.align 2, 0x00
glabel gTextureTinyFontQuestion
.incbin "textures/standalone/tiny_font_question.ia16.mio0"
glabel gTextureTinyFontQuestion_end

.align 2, 0x00
glabel gTexture7EECE4
.incbin "textures/standalone/texture_7EECE4.ia16.mio0"
glabel gTexture7EECE4_end

.align 2, 0x00
glabel gTexture7EED74
.incbin "textures/standalone/texture_7EED74.ia16.mio0"
glabel gTexture7EED74_end

.align 2, 0x00
glabel gTexture7EEDB0
.incbin "textures/standalone/texture_7EEDB0.ia16.mio0"
glabel gTexture7EEDB0_end

.align 2, 0x00
glabel gTexture7EEDE8
.incbin "textures/standalone/texture_7EEDE8.ia16.mio0"
glabel gTexture7EEDE8_end

.align 2, 0x00
glabel gTexture7EEE20
.incbin "textures/standalone/texture_7EEE20.ia16.mio0"
glabel gTexture7EEE20_end

.align 2, 0x00
glabel gTexture7EEE7C
.incbin "textures/standalone/texture_7EEE7C.ia16.mio0"
glabel gTexture7EEE7C_end

.align 2, 0x00
glabel gTexture7EEED0
.incbin "textures/standalone/texture_7EEED0.ia16.mio0"
glabel gTexture7EEED0_end

.align 2, 0x00
glabel gTexture7EEF3C
.incbin "textures/standalone/texture_7EEF3C.ia16.mio0"
glabel gTexture7EEF3C_end

.align 2, 0x00
glabel gTexture7EEF90
.incbin "textures/standalone/texture_7EEF90.ia16.mio0"
glabel gTexture7EEF90_end

.align 2, 0x00
glabel gTexture7EEFF4
.incbin "textures/standalone/texture_7EEFF4.ia16.mio0"
glabel gTexture7EEFF4_end

.align 2, 0x00
glabel gTexture7EF058
.incbin "textures/standalone/texture_7EF058.ia16.mio0"
glabel gTexture7EF058_end

.align 2, 0x00
glabel gTexture7EF0B4
.incbin "textures/standalone/texture_7EF0B4.ia16.mio0"
glabel gTexture7EF0B4_end

.align 2, 0x00
glabel gTexture7EF110
.incbin "textures/standalone/texture_7EF110.ia16.mio0"
glabel gTexture7EF110_end

.align 2, 0x00
glabel gTexture7EF17C
.incbin "textures/standalone/texture_7EF17C.ia16.mio0"
glabel gTexture7EF17C_end

.align 2, 0x00
glabel gTexture7EF1F0
.incbin "textures/standalone/texture_7EF1F0.ia16.mio0"
glabel gTexture7EF1F0_end

.align 2, 0x00
glabel gTexture7EF250
.incbin "textures/standalone/texture_7EF250.ia16.mio0"
glabel gTexture7EF250_end

.align 2, 0x00
glabel gTexture7EF2B8
.incbin "textures/standalone/texture_7EF2B8.ia16.mio0"
glabel gTexture7EF2B8_end

.align 2, 0x00
glabel gTexture7EF314
.incbin "textures/standalone/texture_7EF314.ia16.mio0"
glabel gTexture7EF314_end

.align 2, 0x00
glabel gTexture7EF388
.incbin "textures/standalone/texture_7EF388.ia16.mio0"
glabel gTexture7EF388_end

.align 2, 0x00
glabel gTexture7EF3F8
.incbin "textures/standalone/texture_7EF3F8.ia16.mio0"
glabel gTexture7EF3F8_end

.align 2, 0x00
glabel gTexture7EF470
.incbin "textures/standalone/texture_7EF470.ia16.mio0"
glabel gTexture7EF470_end

.align 2, 0x00
glabel gTexture7EF4E4
.incbin "textures/standalone/texture_7EF4E4.ia16.mio0"
glabel gTexture7EF4E4_end

.align 2, 0x00
glabel gTexture7EF554
.incbin "textures/standalone/texture_7EF554.ia16.mio0"
glabel gTexture7EF554_end

.align 2, 0x00
glabel gTexture7EF5C0
.incbin "textures/standalone/texture_7EF5C0.ia16.mio0"
glabel gTexture7EF5C0_end

.align 2, 0x00
glabel gTexture7EF620
.incbin "textures/standalone/texture_7EF620.ia16.mio0"
glabel gTexture7EF620_end

.align 2, 0x00
glabel gTexture7EF694
.incbin "textures/standalone/texture_7EF694.ia16.mio0"
glabel gTexture7EF694_end

.align 2, 0x00
glabel gTexture7EF708
.incbin "textures/standalone/texture_7EF708.ia16.mio0"
glabel gTexture7EF708_end

.align 2, 0x00
glabel gTexture7EF77C
.incbin "textures/standalone/texture_7EF77C.ia16.mio0"
glabel gTexture7EF77C_end

.align 2, 0x00
glabel gTexture7EF7E8
.incbin "textures/standalone/texture_7EF7E8.ia16.mio0"
glabel gTexture7EF7E8_end

.align 2, 0x00
glabel gTexture7EF85C
.incbin "textures/standalone/texture_7EF85C.ia16.mio0"
glabel gTexture7EF85C_end

.align 2, 0x00
glabel gTexture7EF8C8
.incbin "textures/standalone/texture_7EF8C8.ia16.mio0"
glabel gTexture7EF8C8_end

.align 2, 0x00
glabel gTexture7EF93C
.incbin "textures/standalone/texture_7EF93C.ia16.mio0"
glabel gTexture7EF93C_end

.align 2, 0x00
glabel gTexture7EF9B4
.incbin "textures/standalone/texture_7EF9B4.ia16.mio0"
glabel gTexture7EF9B4_end

.align 2, 0x00
glabel gTexture7EFA2C
.incbin "textures/standalone/texture_7EFA2C.ia16.mio0"
glabel gTexture7EFA2C_end

.align 2, 0x00
glabel gTexture7EFAA8
.incbin "textures/standalone/texture_7EFAA8.ia16.mio0"
glabel gTexture7EFAA8_end

.align 2, 0x00
glabel gTexture7EFB00
.incbin "textures/standalone/texture_7EFB00.ia16.mio0"
glabel gTexture7EFB00_end

.align 2, 0x00
glabel gTexture7EFB64
.incbin "textures/standalone/texture_7EFB64.ia16.mio0"
glabel gTexture7EFB64_end

.align 2, 0x00
glabel gTexture7EFBBC
.incbin "textures/standalone/texture_7EFBBC.ia16.mio0"
glabel gTexture7EFBBC_end

.align 2, 0x00
glabel gTexture7EFC30
.incbin "textures/standalone/texture_7EFC30.ia16.mio0"
glabel gTexture7EFC30_end

.align 2, 0x00
glabel gTexture7EFCAC
.incbin "textures/standalone/texture_7EFCAC.ia16.mio0"
glabel gTexture7EFCAC_end

.align 2, 0x00
glabel gTexture7EFD00
.incbin "textures/standalone/texture_7EFD00.ia16.mio0"
glabel gTexture7EFD00_end

.align 2, 0x00
glabel gTexture7EFD60
.incbin "textures/standalone/texture_7EFD60.ia16.mio0"
glabel gTexture7EFD60_end

.align 2, 0x00
glabel gTexture7EFDD4
.incbin "textures/standalone/texture_7EFDD4.ia16.mio0"
glabel gTexture7EFDD4_end

.align 2, 0x00
glabel gTexture7EFE48
.incbin "textures/standalone/texture_7EFE48.ia16.mio0"
glabel gTexture7EFE48_end

.align 2, 0x00
glabel gTexture7EFEA0
.incbin "textures/standalone/texture_7EFEA0.ia16.mio0"
glabel gTexture7EFEA0_end

.align 2, 0x00
glabel gTexture7EFF2C
.incbin "textures/standalone/texture_7EFF2C.ia16.mio0"
glabel gTexture7EFF2C_end

.align 2, 0x00
glabel gTexture7EFF90
.incbin "textures/standalone/texture_7EFF90.ia16.mio0"
glabel gTexture7EFF90_end

.align 2, 0x00
glabel gTexture7F0000
.incbin "textures/standalone/texture_7F0000.ia16.mio0"
glabel gTexture7F0000_end

.align 2, 0x00
glabel gTexture7F006C
.incbin "textures/standalone/texture_7F006C.ia16.mio0"
glabel gTexture7F006C_end

.align 2, 0x00
glabel gTexture7F00D8
.incbin "textures/standalone/texture_7F00D8.ia16.mio0"
glabel gTexture7F00D8_end

.align 2, 0x00
glabel gTexture7F0158
.incbin "textures/standalone/texture_7F0158.ia16.mio0"
glabel gTexture7F0158_end

.align 2, 0x00
glabel gTexture7F01D0
.incbin "textures/standalone/texture_7F01D0.ia16.mio0"
glabel gTexture7F01D0_end

.align 2, 0x00
glabel gTexture7F023C
.incbin "textures/standalone/texture_7F023C.ia16.mio0"
glabel gTexture7F023C_end

.align 2, 0x00
glabel gTexture7F02B4
.incbin "textures/standalone/texture_7F02B4.ia16.mio0"
glabel gTexture7F02B4_end

.align 2, 0x00
glabel gTexture7F032C
.incbin "textures/standalone/texture_7F032C.ia16.mio0"
glabel gTexture7F032C_end

.align 2, 0x00
glabel gTexture7F0390
.incbin "textures/standalone/texture_7F0390.ia16.mio0"
glabel gTexture7F0390_end

.align 2, 0x00
glabel gTexture7F0404
.incbin "textures/standalone/texture_7F0404.ia16.mio0"
glabel gTexture7F0404_end

.align 2, 0x00
glabel gTexture7F0470
.incbin "textures/standalone/texture_7F0470.ia16.mio0"
glabel gTexture7F0470_end

.align 2, 0x00
glabel gTexture7F04EC
.incbin "textures/standalone/texture_7F04EC.ia16.mio0"
glabel gTexture7F04EC_end

.align 2, 0x00
glabel gTexture7F055C
.incbin "textures/standalone/texture_7F055C.ia16.mio0"
glabel gTexture7F055C_end

.align 2, 0x00
glabel gTexture7F05F0
.incbin "textures/standalone/texture_7F05F0.ia16.mio0"
glabel gTexture7F05F0_end

.align 2, 0x00
glabel gTexture7F0670
.incbin "textures/standalone/texture_7F0670.ia16.mio0"
glabel gTexture7F0670_end

.align 2, 0x00
glabel gTexture7F06EC
.incbin "textures/standalone/texture_7F06EC.ia16.mio0"
glabel gTexture7F06EC_end

.align 2, 0x00
glabel gTexture7F0768
.incbin "textures/standalone/texture_7F0768.ia16.mio0"
glabel gTexture7F0768_end

.align 2, 0x00
glabel gTexture7F07E0
.incbin "textures/standalone/texture_7F07E0.ia16.mio0"
glabel gTexture7F07E0_end

.align 2, 0x00
glabel gTexture7F0858
.incbin "textures/standalone/texture_7F0858.ia16.mio0"
glabel gTexture7F0858_end

.align 2, 0x00
glabel gTexture7F08D8
.incbin "textures/standalone/texture_7F08D8.ia16.mio0"
glabel gTexture7F08D8_end

.align 2, 0x00
glabel gTexture7F0948
.incbin "textures/standalone/texture_7F0948.ia16.mio0"
glabel gTexture7F0948_end

.align 2, 0x00
glabel gTexture7F09D0
.incbin "textures/standalone/texture_7F09D0.ia16.mio0"
glabel gTexture7F09D0_end

.align 2, 0x00
glabel gTexture7F0A3C
.incbin "textures/standalone/texture_7F0A3C.ia16.mio0"
glabel gTexture7F0A3C_end

.align 2, 0x00
glabel gTexture7F0ABC
.incbin "textures/standalone/texture_7F0ABC.ia16.mio0"
glabel gTexture7F0ABC_end

.align 2, 0x00
glabel gTexture7F0B34
.incbin "textures/standalone/texture_7F0B34.ia16.mio0"
glabel gTexture7F0B34_end

.align 2, 0x00
glabel gTexture7F0BB0
.incbin "textures/standalone/texture_7F0BB0.ia16.mio0"
glabel gTexture7F0BB0_end

.align 2, 0x00
glabel gTexture7F0C24
.incbin "textures/standalone/texture_7F0C24.ia16.mio0"
glabel gTexture7F0C24_end

.align 2, 0x00
glabel gTexture7F0C94
.incbin "textures/standalone/texture_7F0C94.ia16.mio0"
glabel gTexture7F0C94_end

.align 2, 0x00
glabel gTexture7F0D0C
.incbin "textures/standalone/texture_7F0D0C.ia16.mio0"
glabel gTexture7F0D0C_end

.align 2, 0x00
glabel gTexture7F0D8C
.incbin "textures/standalone/texture_7F0D8C.ia16.mio0"
glabel gTexture7F0D8C_end

.align 2, 0x00
glabel gTexture7F0DEC
.incbin "textures/standalone/texture_7F0DEC.ia16.mio0"
glabel gTexture7F0DEC_end

.align 2, 0x00
glabel gTexture7F0E5C
.incbin "textures/standalone/texture_7F0E5C.ia16.mio0"
glabel gTexture7F0E5C_end

.align 2, 0x00
glabel gTexture7F0EE4
.incbin "textures/standalone/texture_7F0EE4.ia16.mio0"
glabel gTexture7F0EE4_end

.align 2, 0x00
glabel gTexture7F0F5C
.incbin "textures/standalone/texture_7F0F5C.ia16.mio0"
glabel gTexture7F0F5C_end

.align 2, 0x00
glabel gTexture7F0FD8
.incbin "textures/standalone/texture_7F0FD8.ia16.mio0"
glabel gTexture7F0FD8_end

.align 2, 0x00
glabel gTexture7F1038
.incbin "textures/standalone/texture_7F1038.ia16.mio0"
glabel gTexture7F1038_end

.align 2, 0x00
glabel gTexture7F109C
.incbin "textures/standalone/texture_7F109C.ia16.mio0"
glabel gTexture7F109C_end

/* cn only. The iQue build carries a Chinese glyph set the n64 builds do
   not: 281 glyphs in the same 26x16 i4 shape as the latin font below,
   sitting immediately in front of it. Cart offset 0x7EFF18. */
.ifdef VERSION_CN
.align 2, 0x00
glabel font_cn_000
.incbin "textures/raw/font_cn_000.i4"
glabel font_cn_001
.incbin "textures/raw/font_cn_001.i4"
glabel font_cn_002
.incbin "textures/raw/font_cn_002.i4"
glabel font_cn_003
.incbin "textures/raw/font_cn_003.i4"
glabel font_cn_004
.incbin "textures/raw/font_cn_004.i4"
glabel font_cn_005
.incbin "textures/raw/font_cn_005.i4"
glabel font_cn_006
.incbin "textures/raw/font_cn_006.i4"
glabel font_cn_007
.incbin "textures/raw/font_cn_007.i4"
glabel font_cn_008
.incbin "textures/raw/font_cn_008.i4"
glabel font_cn_009
.incbin "textures/raw/font_cn_009.i4"
glabel font_cn_010
.incbin "textures/raw/font_cn_010.i4"
glabel font_cn_011
.incbin "textures/raw/font_cn_011.i4"
glabel font_cn_012
.incbin "textures/raw/font_cn_012.i4"
glabel font_cn_013
.incbin "textures/raw/font_cn_013.i4"
glabel font_cn_014
.incbin "textures/raw/font_cn_014.i4"
glabel font_cn_015
.incbin "textures/raw/font_cn_015.i4"
glabel font_cn_016
.incbin "textures/raw/font_cn_016.i4"
glabel font_cn_017
.incbin "textures/raw/font_cn_017.i4"
glabel font_cn_018
.incbin "textures/raw/font_cn_018.i4"
glabel font_cn_019
.incbin "textures/raw/font_cn_019.i4"
glabel font_cn_020
.incbin "textures/raw/font_cn_020.i4"
glabel font_cn_021
.incbin "textures/raw/font_cn_021.i4"
glabel font_cn_022
.incbin "textures/raw/font_cn_022.i4"
glabel font_cn_023
.incbin "textures/raw/font_cn_023.i4"
glabel font_cn_024
.incbin "textures/raw/font_cn_024.i4"
glabel font_cn_025
.incbin "textures/raw/font_cn_025.i4"
glabel font_cn_026
.incbin "textures/raw/font_cn_026.i4"
glabel font_cn_027
.incbin "textures/raw/font_cn_027.i4"
glabel font_cn_028
.incbin "textures/raw/font_cn_028.i4"
glabel font_cn_029
.incbin "textures/raw/font_cn_029.i4"
glabel font_cn_030
.incbin "textures/raw/font_cn_030.i4"
glabel font_cn_031
.incbin "textures/raw/font_cn_031.i4"
glabel font_cn_032
.incbin "textures/raw/font_cn_032.i4"
glabel font_cn_033
.incbin "textures/raw/font_cn_033.i4"
glabel font_cn_034
.incbin "textures/raw/font_cn_034.i4"
glabel font_cn_035
.incbin "textures/raw/font_cn_035.i4"
glabel font_cn_036
.incbin "textures/raw/font_cn_036.i4"
glabel font_cn_037
.incbin "textures/raw/font_cn_037.i4"
glabel font_cn_038
.incbin "textures/raw/font_cn_038.i4"
glabel font_cn_039
.incbin "textures/raw/font_cn_039.i4"
glabel font_cn_040
.incbin "textures/raw/font_cn_040.i4"
glabel font_cn_041
.incbin "textures/raw/font_cn_041.i4"
glabel font_cn_042
.incbin "textures/raw/font_cn_042.i4"
glabel font_cn_043
.incbin "textures/raw/font_cn_043.i4"
glabel font_cn_044
.incbin "textures/raw/font_cn_044.i4"
glabel font_cn_045
.incbin "textures/raw/font_cn_045.i4"
glabel font_cn_046
.incbin "textures/raw/font_cn_046.i4"
glabel font_cn_047
.incbin "textures/raw/font_cn_047.i4"
glabel font_cn_048
.incbin "textures/raw/font_cn_048.i4"
glabel font_cn_049
.incbin "textures/raw/font_cn_049.i4"
glabel font_cn_050
.incbin "textures/raw/font_cn_050.i4"
glabel font_cn_051
.incbin "textures/raw/font_cn_051.i4"
glabel font_cn_052
.incbin "textures/raw/font_cn_052.i4"
glabel font_cn_053
.incbin "textures/raw/font_cn_053.i4"
glabel font_cn_054
.incbin "textures/raw/font_cn_054.i4"
glabel font_cn_055
.incbin "textures/raw/font_cn_055.i4"
glabel font_cn_056
.incbin "textures/raw/font_cn_056.i4"
glabel font_cn_057
.incbin "textures/raw/font_cn_057.i4"
glabel font_cn_058
.incbin "textures/raw/font_cn_058.i4"
glabel font_cn_059
.incbin "textures/raw/font_cn_059.i4"
glabel font_cn_060
.incbin "textures/raw/font_cn_060.i4"
glabel font_cn_061
.incbin "textures/raw/font_cn_061.i4"
glabel font_cn_062
.incbin "textures/raw/font_cn_062.i4"
glabel font_cn_063
.incbin "textures/raw/font_cn_063.i4"
glabel font_cn_064
.incbin "textures/raw/font_cn_064.i4"
glabel font_cn_065
.incbin "textures/raw/font_cn_065.i4"
glabel font_cn_066
.incbin "textures/raw/font_cn_066.i4"
glabel font_cn_067
.incbin "textures/raw/font_cn_067.i4"
glabel font_cn_068
.incbin "textures/raw/font_cn_068.i4"
glabel font_cn_069
.incbin "textures/raw/font_cn_069.i4"
glabel font_cn_070
.incbin "textures/raw/font_cn_070.i4"
glabel font_cn_071
.incbin "textures/raw/font_cn_071.i4"
glabel font_cn_072
.incbin "textures/raw/font_cn_072.i4"
glabel font_cn_073
.incbin "textures/raw/font_cn_073.i4"
glabel font_cn_074
.incbin "textures/raw/font_cn_074.i4"
glabel font_cn_075
.incbin "textures/raw/font_cn_075.i4"
glabel font_cn_076
.incbin "textures/raw/font_cn_076.i4"
glabel font_cn_077
.incbin "textures/raw/font_cn_077.i4"
glabel font_cn_078
.incbin "textures/raw/font_cn_078.i4"
glabel font_cn_079
.incbin "textures/raw/font_cn_079.i4"
glabel font_cn_080
.incbin "textures/raw/font_cn_080.i4"
glabel font_cn_081
.incbin "textures/raw/font_cn_081.i4"
glabel font_cn_082
.incbin "textures/raw/font_cn_082.i4"
glabel font_cn_083
.incbin "textures/raw/font_cn_083.i4"
glabel font_cn_084
.incbin "textures/raw/font_cn_084.i4"
glabel font_cn_085
.incbin "textures/raw/font_cn_085.i4"
glabel font_cn_086
.incbin "textures/raw/font_cn_086.i4"
glabel font_cn_087
.incbin "textures/raw/font_cn_087.i4"
glabel font_cn_088
.incbin "textures/raw/font_cn_088.i4"
glabel font_cn_089
.incbin "textures/raw/font_cn_089.i4"
glabel font_cn_090
.incbin "textures/raw/font_cn_090.i4"
glabel font_cn_091
.incbin "textures/raw/font_cn_091.i4"
glabel font_cn_092
.incbin "textures/raw/font_cn_092.i4"
glabel font_cn_093
.incbin "textures/raw/font_cn_093.i4"
glabel font_cn_094
.incbin "textures/raw/font_cn_094.i4"
glabel font_cn_095
.incbin "textures/raw/font_cn_095.i4"
glabel font_cn_096
.incbin "textures/raw/font_cn_096.i4"
glabel font_cn_097
.incbin "textures/raw/font_cn_097.i4"
glabel font_cn_098
.incbin "textures/raw/font_cn_098.i4"
glabel font_cn_099
.incbin "textures/raw/font_cn_099.i4"
glabel font_cn_100
.incbin "textures/raw/font_cn_100.i4"
glabel font_cn_101
.incbin "textures/raw/font_cn_101.i4"
glabel font_cn_102
.incbin "textures/raw/font_cn_102.i4"
glabel font_cn_103
.incbin "textures/raw/font_cn_103.i4"
glabel font_cn_104
.incbin "textures/raw/font_cn_104.i4"
glabel font_cn_105
.incbin "textures/raw/font_cn_105.i4"
glabel font_cn_106
.incbin "textures/raw/font_cn_106.i4"
glabel font_cn_107
.incbin "textures/raw/font_cn_107.i4"
glabel font_cn_108
.incbin "textures/raw/font_cn_108.i4"
glabel font_cn_109
.incbin "textures/raw/font_cn_109.i4"
glabel font_cn_110
.incbin "textures/raw/font_cn_110.i4"
glabel font_cn_111
.incbin "textures/raw/font_cn_111.i4"
glabel font_cn_112
.incbin "textures/raw/font_cn_112.i4"
glabel font_cn_113
.incbin "textures/raw/font_cn_113.i4"
glabel font_cn_114
.incbin "textures/raw/font_cn_114.i4"
glabel font_cn_115
.incbin "textures/raw/font_cn_115.i4"
glabel font_cn_116
.incbin "textures/raw/font_cn_116.i4"
glabel font_cn_117
.incbin "textures/raw/font_cn_117.i4"
glabel font_cn_118
.incbin "textures/raw/font_cn_118.i4"
glabel font_cn_119
.incbin "textures/raw/font_cn_119.i4"
glabel font_cn_120
.incbin "textures/raw/font_cn_120.i4"
glabel font_cn_121
.incbin "textures/raw/font_cn_121.i4"
glabel font_cn_122
.incbin "textures/raw/font_cn_122.i4"
glabel font_cn_123
.incbin "textures/raw/font_cn_123.i4"
glabel font_cn_124
.incbin "textures/raw/font_cn_124.i4"
glabel font_cn_125
.incbin "textures/raw/font_cn_125.i4"
glabel font_cn_126
.incbin "textures/raw/font_cn_126.i4"
glabel font_cn_127
.incbin "textures/raw/font_cn_127.i4"
glabel font_cn_128
.incbin "textures/raw/font_cn_128.i4"
glabel font_cn_129
.incbin "textures/raw/font_cn_129.i4"
glabel font_cn_130
.incbin "textures/raw/font_cn_130.i4"
glabel font_cn_131
.incbin "textures/raw/font_cn_131.i4"
glabel font_cn_132
.incbin "textures/raw/font_cn_132.i4"
glabel font_cn_133
.incbin "textures/raw/font_cn_133.i4"
glabel font_cn_134
.incbin "textures/raw/font_cn_134.i4"
glabel font_cn_135
.incbin "textures/raw/font_cn_135.i4"
glabel font_cn_136
.incbin "textures/raw/font_cn_136.i4"
glabel font_cn_137
.incbin "textures/raw/font_cn_137.i4"
glabel font_cn_138
.incbin "textures/raw/font_cn_138.i4"
glabel font_cn_139
.incbin "textures/raw/font_cn_139.i4"
glabel font_cn_140
.incbin "textures/raw/font_cn_140.i4"
glabel font_cn_141
.incbin "textures/raw/font_cn_141.i4"
glabel font_cn_142
.incbin "textures/raw/font_cn_142.i4"
glabel font_cn_143
.incbin "textures/raw/font_cn_143.i4"
glabel font_cn_144
.incbin "textures/raw/font_cn_144.i4"
glabel font_cn_145
.incbin "textures/raw/font_cn_145.i4"
glabel font_cn_146
.incbin "textures/raw/font_cn_146.i4"
glabel font_cn_147
.incbin "textures/raw/font_cn_147.i4"
glabel font_cn_148
.incbin "textures/raw/font_cn_148.i4"
glabel font_cn_149
.incbin "textures/raw/font_cn_149.i4"
glabel font_cn_150
.incbin "textures/raw/font_cn_150.i4"
glabel font_cn_151
.incbin "textures/raw/font_cn_151.i4"
glabel font_cn_152
.incbin "textures/raw/font_cn_152.i4"
glabel font_cn_153
.incbin "textures/raw/font_cn_153.i4"
glabel font_cn_154
.incbin "textures/raw/font_cn_154.i4"
glabel font_cn_155
.incbin "textures/raw/font_cn_155.i4"
glabel font_cn_156
.incbin "textures/raw/font_cn_156.i4"
glabel font_cn_157
.incbin "textures/raw/font_cn_157.i4"
glabel font_cn_158
.incbin "textures/raw/font_cn_158.i4"
glabel font_cn_159
.incbin "textures/raw/font_cn_159.i4"
glabel font_cn_160
.incbin "textures/raw/font_cn_160.i4"
glabel font_cn_161
.incbin "textures/raw/font_cn_161.i4"
glabel font_cn_162
.incbin "textures/raw/font_cn_162.i4"
glabel font_cn_163
.incbin "textures/raw/font_cn_163.i4"
glabel font_cn_164
.incbin "textures/raw/font_cn_164.i4"
glabel font_cn_165
.incbin "textures/raw/font_cn_165.i4"
glabel font_cn_166
.incbin "textures/raw/font_cn_166.i4"
glabel font_cn_167
.incbin "textures/raw/font_cn_167.i4"
glabel font_cn_168
.incbin "textures/raw/font_cn_168.i4"
glabel font_cn_169
.incbin "textures/raw/font_cn_169.i4"
glabel font_cn_170
.incbin "textures/raw/font_cn_170.i4"
glabel font_cn_171
.incbin "textures/raw/font_cn_171.i4"
glabel font_cn_172
.incbin "textures/raw/font_cn_172.i4"
glabel font_cn_173
.incbin "textures/raw/font_cn_173.i4"
glabel font_cn_174
.incbin "textures/raw/font_cn_174.i4"
glabel font_cn_175
.incbin "textures/raw/font_cn_175.i4"
glabel font_cn_176
.incbin "textures/raw/font_cn_176.i4"
glabel font_cn_177
.incbin "textures/raw/font_cn_177.i4"
glabel font_cn_178
.incbin "textures/raw/font_cn_178.i4"
glabel font_cn_179
.incbin "textures/raw/font_cn_179.i4"
glabel font_cn_180
.incbin "textures/raw/font_cn_180.i4"
glabel font_cn_181
.incbin "textures/raw/font_cn_181.i4"
glabel font_cn_182
.incbin "textures/raw/font_cn_182.i4"
glabel font_cn_183
.incbin "textures/raw/font_cn_183.i4"
glabel font_cn_184
.incbin "textures/raw/font_cn_184.i4"
glabel font_cn_185
.incbin "textures/raw/font_cn_185.i4"
glabel font_cn_186
.incbin "textures/raw/font_cn_186.i4"
glabel font_cn_187
.incbin "textures/raw/font_cn_187.i4"
glabel font_cn_188
.incbin "textures/raw/font_cn_188.i4"
glabel font_cn_189
.incbin "textures/raw/font_cn_189.i4"
glabel font_cn_190
.incbin "textures/raw/font_cn_190.i4"
glabel font_cn_191
.incbin "textures/raw/font_cn_191.i4"
glabel font_cn_192
.incbin "textures/raw/font_cn_192.i4"
glabel font_cn_193
.incbin "textures/raw/font_cn_193.i4"
glabel font_cn_194
.incbin "textures/raw/font_cn_194.i4"
glabel font_cn_195
.incbin "textures/raw/font_cn_195.i4"
glabel font_cn_196
.incbin "textures/raw/font_cn_196.i4"
glabel font_cn_197
.incbin "textures/raw/font_cn_197.i4"
glabel font_cn_198
.incbin "textures/raw/font_cn_198.i4"
glabel font_cn_199
.incbin "textures/raw/font_cn_199.i4"
glabel font_cn_200
.incbin "textures/raw/font_cn_200.i4"
glabel font_cn_201
.incbin "textures/raw/font_cn_201.i4"
glabel font_cn_202
.incbin "textures/raw/font_cn_202.i4"
glabel font_cn_203
.incbin "textures/raw/font_cn_203.i4"
glabel font_cn_204
.incbin "textures/raw/font_cn_204.i4"
glabel font_cn_205
.incbin "textures/raw/font_cn_205.i4"
glabel font_cn_206
.incbin "textures/raw/font_cn_206.i4"
glabel font_cn_207
.incbin "textures/raw/font_cn_207.i4"
glabel font_cn_208
.incbin "textures/raw/font_cn_208.i4"
glabel font_cn_209
.incbin "textures/raw/font_cn_209.i4"
glabel font_cn_210
.incbin "textures/raw/font_cn_210.i4"
glabel font_cn_211
.incbin "textures/raw/font_cn_211.i4"
glabel font_cn_212
.incbin "textures/raw/font_cn_212.i4"
glabel font_cn_213
.incbin "textures/raw/font_cn_213.i4"
glabel font_cn_214
.incbin "textures/raw/font_cn_214.i4"
glabel font_cn_215
.incbin "textures/raw/font_cn_215.i4"
glabel font_cn_216
.incbin "textures/raw/font_cn_216.i4"
glabel font_cn_217
.incbin "textures/raw/font_cn_217.i4"
glabel font_cn_218
.incbin "textures/raw/font_cn_218.i4"
glabel font_cn_219
.incbin "textures/raw/font_cn_219.i4"
glabel font_cn_220
.incbin "textures/raw/font_cn_220.i4"
glabel font_cn_221
.incbin "textures/raw/font_cn_221.i4"
glabel font_cn_222
.incbin "textures/raw/font_cn_222.i4"
glabel font_cn_223
.incbin "textures/raw/font_cn_223.i4"
glabel font_cn_224
.incbin "textures/raw/font_cn_224.i4"
glabel font_cn_225
.incbin "textures/raw/font_cn_225.i4"
glabel font_cn_226
.incbin "textures/raw/font_cn_226.i4"
glabel font_cn_227
.incbin "textures/raw/font_cn_227.i4"
glabel font_cn_228
.incbin "textures/raw/font_cn_228.i4"
glabel font_cn_229
.incbin "textures/raw/font_cn_229.i4"
glabel font_cn_230
.incbin "textures/raw/font_cn_230.i4"
glabel font_cn_231
.incbin "textures/raw/font_cn_231.i4"
glabel font_cn_232
.incbin "textures/raw/font_cn_232.i4"
glabel font_cn_233
.incbin "textures/raw/font_cn_233.i4"
glabel font_cn_234
.incbin "textures/raw/font_cn_234.i4"
glabel font_cn_235
.incbin "textures/raw/font_cn_235.i4"
glabel font_cn_236
.incbin "textures/raw/font_cn_236.i4"
glabel font_cn_237
.incbin "textures/raw/font_cn_237.i4"
glabel font_cn_238
.incbin "textures/raw/font_cn_238.i4"
glabel font_cn_239
.incbin "textures/raw/font_cn_239.i4"
glabel font_cn_240
.incbin "textures/raw/font_cn_240.i4"
glabel font_cn_241
.incbin "textures/raw/font_cn_241.i4"
glabel font_cn_242
.incbin "textures/raw/font_cn_242.i4"
glabel font_cn_243
.incbin "textures/raw/font_cn_243.i4"
glabel font_cn_244
.incbin "textures/raw/font_cn_244.i4"
glabel font_cn_245
.incbin "textures/raw/font_cn_245.i4"
glabel font_cn_246
.incbin "textures/raw/font_cn_246.i4"
glabel font_cn_247
.incbin "textures/raw/font_cn_247.i4"
glabel font_cn_248
.incbin "textures/raw/font_cn_248.i4"
glabel font_cn_249
.incbin "textures/raw/font_cn_249.i4"
glabel font_cn_250
.incbin "textures/raw/font_cn_250.i4"
glabel font_cn_251
.incbin "textures/raw/font_cn_251.i4"
glabel font_cn_252
.incbin "textures/raw/font_cn_252.i4"
glabel font_cn_253
.incbin "textures/raw/font_cn_253.i4"
glabel font_cn_254
.incbin "textures/raw/font_cn_254.i4"
glabel font_cn_255
.incbin "textures/raw/font_cn_255.i4"
glabel font_cn_256
.incbin "textures/raw/font_cn_256.i4"
glabel font_cn_257
.incbin "textures/raw/font_cn_257.i4"
glabel font_cn_258
.incbin "textures/raw/font_cn_258.i4"
glabel font_cn_259
.incbin "textures/raw/font_cn_259.i4"
glabel font_cn_260
.incbin "textures/raw/font_cn_260.i4"
glabel font_cn_261
.incbin "textures/raw/font_cn_261.i4"
glabel font_cn_262
.incbin "textures/raw/font_cn_262.i4"
glabel font_cn_263
.incbin "textures/raw/font_cn_263.i4"
glabel font_cn_264
.incbin "textures/raw/font_cn_264.i4"
glabel font_cn_265
.incbin "textures/raw/font_cn_265.i4"
glabel font_cn_266
.incbin "textures/raw/font_cn_266.i4"
glabel font_cn_267
.incbin "textures/raw/font_cn_267.i4"
glabel font_cn_268
.incbin "textures/raw/font_cn_268.i4"
glabel font_cn_269
.incbin "textures/raw/font_cn_269.i4"
glabel font_cn_270
.incbin "textures/raw/font_cn_270.i4"
glabel font_cn_271
.incbin "textures/raw/font_cn_271.i4"
glabel font_cn_272
.incbin "textures/raw/font_cn_272.i4"
glabel font_cn_273
.incbin "textures/raw/font_cn_273.i4"
glabel font_cn_274
.incbin "textures/raw/font_cn_274.i4"
glabel font_cn_275
.incbin "textures/raw/font_cn_275.i4"
glabel font_cn_276
.incbin "textures/raw/font_cn_276.i4"
glabel font_cn_277
.incbin "textures/raw/font_cn_277.i4"
glabel font_cn_278
.incbin "textures/raw/font_cn_278.i4"
glabel font_cn_279
.incbin "textures/raw/font_cn_279.i4"
glabel font_cn_280
.incbin "textures/raw/font_cn_280.i4"
.endif

.align 2, 0x00
glabel font_four_dote
.incbin "textures/raw/font_four_dote.i4"

.align 2, 0x00
glabel font_cc
.incbin "textures/raw/font_cc.i4"

.align 2, 0x00
glabel font_double_quote
.incbin "textures/raw/font_double_quote.i4"

.align 2, 0x00
glabel font_exclamation_mark
.incbin "textures/raw/font_exclamation_mark.i4"

.align 2, 0x00
glabel font_minus
.incbin "textures/raw/font_minus.i4"

.align 2, 0x00
glabel font_dot
.incbin "textures/raw/font_dot.i4"

.align 2, 0x00
glabel font_plus
.incbin "textures/raw/font_plus.i4"

.align 2, 0x00
glabel font_interogation_mark
.incbin "textures/raw/font_interogation_mark.i4"

.align 2, 0x00
glabel font_simple_quote
.incbin "textures/raw/font_simple_quote.i4"

.align 2, 0x00
glabel font_number_zero
.incbin "textures/raw/font_number_zero.i4"

.align 2, 0x00
glabel font_number_one
.incbin "textures/raw/font_number_one.i4"

.align 2, 0x00
glabel font_number_two
.incbin "textures/raw/font_number_two.i4"

.align 2, 0x00
glabel font_number_three
.incbin "textures/raw/font_number_three.i4"

.align 2, 0x00
glabel font_number_four
.incbin "textures/raw/font_number_four.i4"

.align 2, 0x00
glabel font_number_five
.incbin "textures/raw/font_number_five.i4"

.align 2, 0x00
glabel font_number_six
.incbin "textures/raw/font_number_six.i4"

.align 2, 0x00
glabel font_number_seven
.incbin "textures/raw/font_number_seven.i4"

.align 2, 0x00
glabel font_number_eight
.incbin "textures/raw/font_number_eight.i4"

.align 2, 0x00
glabel font_number_nine
.incbin "textures/raw/font_number_nine.i4"

.align 2, 0x00
glabel font_letter_A
.incbin "textures/raw/font_letter_A.i4"

.align 2, 0x00
glabel font_letter_B
.incbin "textures/raw/font_letter_B.i4"

.align 2, 0x00
glabel font_letter_C
.incbin "textures/raw/font_letter_C.i4"

.align 2, 0x00
glabel font_letter_D
.incbin "textures/raw/font_letter_D.i4"

.align 2, 0x00
glabel font_letter_E
.incbin "textures/raw/font_letter_E.i4"

.align 2, 0x00
glabel font_letter_F
.incbin "textures/raw/font_letter_F.i4"

.align 2, 0x00
glabel font_letter_G
.incbin "textures/raw/font_letter_G.i4"

.align 2, 0x00
glabel font_letter_H
.incbin "textures/raw/font_letter_H.i4"

.align 2, 0x00
glabel font_letter_I
.incbin "textures/raw/font_letter_I.i4"

.align 2, 0x00
glabel font_letter_J
.incbin "textures/raw/font_letter_J.i4"

.align 2, 0x00
glabel font_letter_K
.incbin "textures/raw/font_letter_K.i4"

.align 2, 0x00
glabel font_letter_L
.incbin "textures/raw/font_letter_L.i4"

.align 2, 0x00
glabel font_letter_M
.incbin "textures/raw/font_letter_M.i4"

.align 2, 0x00
glabel font_letter_N
.incbin "textures/raw/font_letter_N.i4"

.align 2, 0x00
glabel font_letter_O
.incbin "textures/raw/font_letter_O.i4"

.align 2, 0x00
glabel font_letter_P
.incbin "textures/raw/font_letter_P.i4"

.align 2, 0x00
glabel font_letter_Q
.incbin "textures/raw/font_letter_Q.i4"

.align 2, 0x00
glabel font_letter_R
.incbin "textures/raw/font_letter_R.i4"

.align 2, 0x00
glabel font_letter_S
.incbin "textures/raw/font_letter_S.i4"

.align 2, 0x00
glabel font_letter_T
.incbin "textures/raw/font_letter_T.i4"

.align 2, 0x00
glabel font_letter_U
.incbin "textures/raw/font_letter_U.i4"

.align 2, 0x00
glabel font_letter_V
.incbin "textures/raw/font_letter_V.i4"

.align 2, 0x00
glabel font_letter_W
.incbin "textures/raw/font_letter_W.i4"

.align 2, 0x00
glabel font_letter_X
.incbin "textures/raw/font_letter_X.i4"

.align 2, 0x00
glabel font_letter_Y
.incbin "textures/raw/font_letter_Y.i4"

.align 2, 0x00
glabel font_letter_Z
.incbin "textures/raw/font_letter_Z.i4"

.align 2, 0x00
glabel gTexture7F35B4
.incbin "textures/raw/7F35B4.i4"

.align 2, 0x00
glabel gTexture7F3634
.incbin "textures/raw/7F3634.i4"

.align 2, 0x00
glabel gTexture7F36B4
.incbin "textures/raw/7F36B4.i4"

.align 2, 0x00
glabel gTexture7F3734
.incbin "textures/raw/7F3734.i4"

.align 2, 0x00
glabel gTexture7F37B4
.incbin "textures/raw/7F37B4.i4"

.align 2, 0x00
glabel gTexture7F3834
.incbin "textures/raw/7F3834.i4"

.align 2, 0x00
glabel gTexture7F38B4
.incbin "textures/raw/7F38B4.i4"

.align 2, 0x00
glabel gTexture7F3934
.incbin "textures/raw/7F3934.i4"

.align 2, 0x00
glabel gTexture7F39B4
.incbin "textures/raw/7F39B4.i4"

.align 2, 0x00
glabel gTexture7F3A34
.incbin "textures/raw/7F3A34.i4"

.align 2, 0x00
glabel gTexture7F3AB4
.incbin "textures/raw/7F3AB4.i4"

.align 2, 0x00
glabel gTexture7F3B34
.incbin "textures/raw/7F3B34.i4"

.align 2, 0x00
glabel gTexture7F3BB4
.incbin "textures/raw/7F3BB4.i4"

.align 2, 0x00
glabel gTexture7F3C34
.incbin "textures/raw/7F3C34.i4"

.align 2, 0x00
glabel gTexture7F3CB4
.incbin "textures/raw/7F3CB4.i4"

.align 2, 0x00
glabel gTexture7F3D34
.incbin "textures/raw/7F3D34.i4"

.align 2, 0x00
glabel gTexture7F3DB4
.incbin "textures/raw/7F3DB4.i4"

.align 2, 0x00
glabel gTexture7F3E34
.incbin "textures/raw/7F3E34.i4"

.align 2, 0x00
glabel gTexture7F3EB4
.incbin "textures/raw/7F3EB4.i4"

.align 2, 0x00
glabel gTexture7F3F34
.incbin "textures/raw/7F3F34.i4"

.align 2, 0x00
glabel gTexture7F3FB4
.incbin "textures/raw/7F3FB4.i4"

.align 2, 0x00
glabel gTexture7F4034
.incbin "textures/raw/7F4034.i4"

.align 2, 0x00
glabel gTexture7F40B4
.incbin "textures/raw/7F40B4.i4"

.align 2, 0x00
glabel gTexture7F4134
.incbin "textures/raw/7F4134.i4"

.align 2, 0x00
glabel gTexture7F41B4
.incbin "textures/raw/7F41B4.i4"

.align 2, 0x00
glabel gTexture7F4234
.incbin "textures/raw/7F4234.i4"

.align 2, 0x00
glabel gTexture7F42B4
.incbin "textures/raw/7F42B4.i4"

.align 2, 0x00
glabel gTexture7F4334
.incbin "textures/raw/7F4334.i4"

.align 2, 0x00
glabel gTexture7F43B4
.incbin "textures/raw/7F43B4.i4"

.align 2, 0x00
glabel gTexture7F4434
.incbin "textures/raw/7F4434.i4"

.align 2, 0x00
glabel gTexture7F44B4
.incbin "textures/raw/7F44B4.i4"

.align 2, 0x00
glabel gTexture7F4534
.incbin "textures/raw/7F4534.i4"

.align 2, 0x00
glabel gTexture7F45B4
.incbin "textures/raw/7F45B4.i4"

.align 2, 0x00
glabel gTexture7F4634
.incbin "textures/raw/7F4634.i4"

.align 2, 0x00
glabel gTexture7F46B4
.incbin "textures/raw/7F46B4.i4"

.align 2, 0x00
glabel gTexture7F4734
.incbin "textures/raw/7F4734.i4"

.align 2, 0x00
glabel gTexture7F47B4
.incbin "textures/raw/7F47B4.i4"

.align 2, 0x00
glabel gTexture7F4834
.incbin "textures/raw/7F4834.i4"

.align 2, 0x00
glabel gTexture7F48B4
.incbin "textures/raw/7F48B4.i4"

.align 2, 0x00
glabel gTexture7F4934
.incbin "textures/raw/7F4934.i4"

.align 2, 0x00
glabel gTexture7F49B4
.incbin "textures/raw/7F49B4.i4"

.align 2, 0x00
glabel gTexture7F4A34
.incbin "textures/raw/7F4A34.i4"

.align 2, 0x00
glabel gTexture7F4AB4
.incbin "textures/raw/7F4AB4.i4"

.align 2, 0x00
glabel gTexture7F4B34
.incbin "textures/raw/7F4B34.i4"

.align 2, 0x00
glabel gTexture7F4BB4
.incbin "textures/raw/7F4BB4.i4"

.align 2, 0x00
glabel gTexture7F4C34
.incbin "textures/raw/7F4C34.i4"

.align 2, 0x00
glabel gTexture7F4CB4
.incbin "textures/raw/7F4CB4.i4"

.align 2, 0x00
glabel gTexture7F4D34
.incbin "textures/raw/7F4D34.i4"

.align 2, 0x00
glabel gTexture7F4DB4
.incbin "textures/raw/7F4DB4.i4"

.align 2, 0x00
glabel gTexture7F4E34
.incbin "textures/raw/7F4E34.i4"

.align 2, 0x00
glabel gTexture7F4EB4
.incbin "textures/raw/7F4EB4.i4"

.align 2, 0x00
glabel gTexture7F4F34
.incbin "textures/raw/7F4F34.i4"

.align 2, 0x00
glabel gTexture7F4FB4
.incbin "textures/raw/7F4FB4.i4"

.align 2, 0x00
glabel gTexture7F5034
.incbin "textures/raw/7F5034.i4"

.align 2, 0x00
glabel gTexture7F50B4
.incbin "textures/raw/7F50B4.i4"

.align 2, 0x00
glabel gTexture7F5134
.incbin "textures/raw/7F5134.i4"

.align 2, 0x00
glabel gTexture7F51B4
.incbin "textures/raw/7F51B4.i4"

.align 2, 0x00
glabel gTexture7F5234
.incbin "textures/raw/7F5234.i4"

.align 2, 0x00
glabel gTexture7F52B4
.incbin "textures/raw/7F52B4.i4"

.align 2, 0x00
glabel gTexture7F5334
.incbin "textures/raw/7F5334.i4"

.align 2, 0x00
glabel gTexture7F53B4
.incbin "textures/raw/7F53B4.i4"

.align 2, 0x00
glabel gTexture7F5434
.incbin "textures/raw/7F5434.i4"

.align 2, 0x00
glabel gTexture7F54B4
.incbin "textures/raw/7F54B4.i4"

.align 2, 0x00
glabel gTexture7F5534
.incbin "textures/raw/7F5534.i4"

.align 2, 0x00
glabel gTexture7F55B4
.incbin "textures/raw/7F55B4.i4"

.align 2, 0x00
glabel gTexture7F5634
.incbin "textures/raw/7F5634.i4"

.align 2, 0x00
glabel gTexture7F56B4
.incbin "textures/raw/7F56B4.i4"

.align 2, 0x00
glabel gTexture7F5734
.incbin "textures/raw/7F5734.i4"

.align 2, 0x00
glabel gTexture7F57B4
.incbin "textures/raw/7F57B4.i4"

.align 2, 0x00
glabel gTexture7F5834
.incbin "textures/raw/7F5834.i4"

.align 2, 0x00
glabel gTexture7F58B4
.incbin "textures/raw/7F58B4.i4"

.align 2, 0x00
glabel gTexture7F5934
.incbin "textures/raw/7F5934.i4"

.align 2, 0x00
glabel gTexture7F59B4
.incbin "textures/raw/7F59B4.i4"

.align 2, 0x00
glabel gTexture7F5A34
.incbin "textures/raw/7F5A34.i4"

.align 2, 0x00
glabel gTexture7F5AB4
.incbin "textures/raw/7F5AB4.i4"

.align 2, 0x00
glabel gTexture7F5B34
.incbin "textures/raw/7F5B34.i4"

.align 2, 0x00
glabel gTexture7F5BB4
.incbin "textures/raw/7F5BB4.i4"

.align 2, 0x00
glabel gTexture7F5C34
.incbin "textures/raw/7F5C34.i4"

.align 2, 0x00
glabel gTexture7F5CB4
.incbin "textures/raw/7F5CB4.i4"

.align 2, 0x00
glabel gTexture7F5D34
.incbin "textures/raw/7F5D34.i4"

.align 2, 0x00
glabel gTexture7F5DB4
.incbin "textures/raw/7F5DB4.i4"

.align 2, 0x00
glabel gTexture7F5E34
.incbin "textures/raw/7F5E34.i4"

.align 2, 0x00
glabel gTexture7F5EB4
.incbin "textures/raw/7F5EB4.i4"

.align 2, 0x00
glabel gTexture7F5F34
.incbin "textures/raw/7F5F34.i4"

.align 2, 0x00
glabel gTexture7F5FB4
.incbin "textures/raw/7F5FB4.i4"

.align 2, 0x00
glabel gTexture7F6034
.incbin "textures/raw/7F6034.i4"

.align 2, 0x00
glabel gTexture7F60B4
.incbin "textures/raw/7F60B4.i4"

.align 2, 0x00
glabel gTexture7F6134
.incbin "textures/raw/7F6134.i4"

.align 2, 0x00
glabel gTexture7F61B4
.incbin "textures/raw/7F61B4.i4"

.align 2, 0x00
glabel gTexture7F6234
.incbin "textures/raw/7F6234.i4"

.align 2, 0x00
glabel gTexture7F62B4
.incbin "textures/raw/7F62B4.i4"

.align 2, 0x00
glabel gTexture7F6334
.incbin "textures/raw/7F6334.i4"

.align 2, 0x00
glabel gTexture7F63B4
.incbin "textures/raw/7F63B4.i4"

.align 2, 0x00
glabel gTexture7F6434
.incbin "textures/raw/7F6434.i4"

.align 2, 0x00
glabel gTexture7F64B4
.incbin "textures/raw/7F64B4.i4"

.align 2, 0x00
glabel gTexture7F6534
.incbin "textures/raw/7F6534.i4"

.align 2, 0x00
glabel gTexture7F65B4
.incbin "textures/raw/7F65B4.i4"

.align 2, 0x00
glabel gTexture7F6634
.incbin "textures/raw/7F6634.i4"

.align 2, 0x00
glabel gTexture7F66B4
.incbin "textures/raw/7F66B4.i4"

.align 2, 0x00
glabel gTexture7F6734
.incbin "textures/raw/7F6734.i4"

.align 2, 0x00
glabel gTexture7F67B4
.incbin "textures/raw/7F67B4.i4"

.align 2, 0x00
glabel gTexture7F6834
.incbin "textures/raw/7F6834.i4"

.align 2, 0x00
glabel gTexture7F68B4
.incbin "textures/raw/7F68B4.i4"

.align 2, 0x00
glabel gTexture7F6934
.incbin "textures/raw/7F6934.i4"

.align 2, 0x00
glabel gTexture7F69B4
.incbin "textures/raw/7F69B4.i4"

.align 2, 0x00
glabel gTexture7F6A34
.incbin "textures/raw/7F6A34.i4"

.align 2, 0x00
glabel gTexture7F6AB4
.incbin "textures/raw/7F6AB4.i4"

.align 2, 0x00
glabel gTexture7F6B34
.incbin "textures/raw/7F6B34.i4"

.align 2, 0x00
glabel gTexture7F6BB4
.incbin "textures/raw/7F6BB4.i4"

.align 2, 0x00
glabel gTexture7F6C34
.incbin "textures/raw/7F6C34.i4"

.align 2, 0x00
glabel gTexture7F6CB4
.incbin "textures/raw/7F6CB4.i4"

.align 2, 0x00
glabel gTexture7F6D34
.incbin "textures/raw/7F6D34.i4"

.align 2, 0x00
glabel gTexture7F6DB4
.incbin "textures/raw/7F6DB4.i4"

.align 2, 0x00
glabel gTexture7F6E34
.incbin "textures/raw/7F6E34.i4"

.align 2, 0x00
glabel gTexture7F6EB4
.incbin "textures/raw/7F6EB4.i4"

.align 2, 0x00
glabel gTexture7F6F34
.incbin "textures/raw/7F6F34.i4"

.align 2, 0x00
glabel gTexture7F6FB4
.incbin "textures/raw/7F6FB4.i4"

.align 2, 0x00
glabel gTexture7F7034
.incbin "textures/raw/7F7034.i4"

.align 2, 0x00
glabel gTexture7F70B4
.incbin "textures/raw/7F70B4.i4"

.align 2, 0x00
glabel gTexture7F7134
.incbin "textures/raw/7F7134.i4"

.align 2, 0x00
glabel gTexture7F71B4
.incbin "textures/raw/7F71B4.i4"

.align 2, 0x00
glabel gTexture7F7234
.incbin "textures/raw/7F7234.i4"

.align 2, 0x00
glabel gTexture7F72B4
.incbin "textures/raw/7F72B4.i4"

.align 2, 0x00
glabel gTexture7F7334
.incbin "textures/raw/7F7334.i4"

.align 2, 0x00
glabel gTexture7F73B4
.incbin "textures/raw/7F73B4.i4"

.align 2, 0x00
glabel gTexture7F7434
.incbin "textures/raw/7F7434.i4"

.align 2, 0x00
glabel gTexture7F74B4
.incbin "textures/raw/7F74B4.i4"

.align 2, 0x00
glabel gTexture7F7534
.incbin "textures/raw/7F7534.i4"

.align 2, 0x00
glabel gTexture7F75B4
.incbin "textures/raw/7F75B4.i4"

.align 2, 0x00
glabel gTexture7F7634
.incbin "textures/raw/7F7634.i4"

.align 2, 0x00
glabel gTexture7F76B4
.incbin "textures/raw/7F76B4.i4"

.align 2, 0x00
glabel gTexture7F7734
.incbin "textures/raw/7F7734.i4"

.align 2, 0x00
glabel gTexture7F77B4
.incbin "textures/raw/7F77B4.i4"

.align 2, 0x00
glabel gTexture7F7834
.incbin "textures/raw/7F7834.i4"

.align 2, 0x00
glabel gTexture7F78B4
.incbin "textures/raw/7F78B4.i4"

.align 2, 0x00
glabel gTexture7F7934
.incbin "textures/raw/7F7934.i4"

.align 2, 0x00
glabel gTexture7F79B4
.incbin "textures/raw/7F79B4.i4"

.align 2, 0x00
glabel gTexture7F7A34
.incbin "textures/raw/7F7A34.i4"

.align 2, 0x00
glabel gTexture7F7AB4
.incbin "textures/raw/7F7AB4.i4"

.align 2, 0x00
glabel gTexture7F7B34
.incbin "textures/raw/7F7B34.i4"

.align 2, 0x00
glabel gTexture7F7BB4
.incbin "textures/raw/7F7BB4.i4"

.align 2, 0x00
glabel gTexture7F7C34
.incbin "textures/raw/7F7C34.i4"

.align 2, 0x00
glabel gTexture7F7CB4
.incbin "textures/raw/7F7CB4.i4"

.align 2, 0x00
glabel gTexture7F7D34
.incbin "textures/raw/7F7D34.i4"

.align 2, 0x00
glabel gTexture7F7DB4
.incbin "textures/raw/7F7DB4.i4"

.align 2, 0x00
glabel gTexture7F7E34
.incbin "textures/raw/7F7E34.i4"

.align 2, 0x00
glabel gTexture7F7EB4
.incbin "textures/raw/7F7EB4.i4"

.align 2, 0x00
glabel gTexture7F7F34
.incbin "textures/raw/7F7F34.i4"

.align 2, 0x00
glabel gTexture7F7FB4
.incbin "textures/raw/7F7FB4.i4"

.align 2, 0x00
glabel gTexture7F8034
.incbin "textures/raw/7F8034.i4"

.align 2, 0x00
glabel gTexture7F80B4
.incbin "textures/raw/7F80B4.i4"

.align 2, 0x00
glabel gTexture7F8134
.incbin "textures/raw/7F8134.i4"

.align 2, 0x00
glabel gTexture7F81B4
.incbin "textures/raw/7F81B4.i4"

.align 2, 0x00
glabel gTexture7F8234
.incbin "textures/raw/7F8234.i4"

.align 2, 0x00
glabel gTexture7F82B4
.incbin "textures/raw/7F82B4.i4"

.align 2, 0x00
glabel gTexture7F8334
.incbin "textures/raw/7F8334.i4"

.align 2, 0x00
glabel gTexture7F83B4
.incbin "textures/raw/7F83B4.i4"

.align 2, 0x00
glabel gTexture7F8434
.incbin "textures/raw/7F8434.i4"

.align 2, 0x00
glabel gTexture7F84B4
.incbin "textures/raw/7F84B4.i4"

.align 2, 0x00
glabel gTexture7F8534
.incbin "textures/raw/7F8534.i4"

.align 2, 0x00
glabel gTexture7F85B4
.incbin "textures/raw/7F85B4.i4"

.align 2, 0x00
glabel gTexture7F8634
.incbin "textures/raw/7F8634.i4"

.align 2, 0x00
glabel gTexture7F86B4
.incbin "textures/raw/7F86B4.i4"

.align 2, 0x00
glabel gTexture7F8734
.incbin "textures/raw/7F8734.i4"

.align 2, 0x00
glabel gTexture7F8914
.incbin "textures/raw/7F8914.i4"

.align 2, 0x00
glabel gTexture7F8AF4
.incbin "textures/raw/7F8AF4.i4"

.align 2, 0x00
glabel gTexture7F8CD4
.incbin "textures/raw/7F8CD4.i4"

.align 2, 0x00
glabel gTexture7F8EB4
.incbin "textures/raw/7F8EB4.i4"

.align 2, 0x00
glabel gTexture7F9094
.incbin "textures/raw/7F9094.i4"

.align 2, 0x00
glabel gTexture7F9274
.incbin "textures/raw/7F9274.i4"

.align 2, 0x00
glabel gTexture7F9454
.incbin "textures/raw/7F9454.i4"

.align 2, 0x00
glabel gTexture7F9634
.incbin "textures/raw/7F9634.i4"

.align 2, 0x00
glabel gTexture7F9814
.incbin "textures/raw/7F9814.i4"

.align 2, 0x00
glabel gTexture7F99F4
.incbin "textures/raw/7F99F4.i4"

.align 2, 0x00
glabel gTexture7F9A74
.incbin "textures/raw/7F9A74.i4"

.align 2, 0x00
glabel gTexture7F9AF4
.incbin "textures/raw/7F9AF4.i4"

.align 2, 0x00
glabel gTexture7F9B74
.incbin "textures/raw/7F9B74.i4"

.align 2, 0x00
glabel gTexture7F9BF4
.incbin "textures/raw/7F9BF4.i4"

.align 2, 0x00
glabel gTexture7F9C74
.incbin "textures/raw/7F9C74.i4"

.align 2, 0x00
glabel gTexture7F9CF4
.incbin "textures/raw/7F9CF4.i4"

.align 2, 0x00
glabel gTexture7F9DC4
.incbin "textures/raw/7F9DC4.i4"

.align 2, 0x00
glabel gTexture7F9E44
.incbin "textures/raw/7F9E44.i4"

.align 2, 0x00
glabel gTexture7F9EC4
.incbin "textures/raw/7F9EC4.i4"

.align 2, 0x00
glabel gTexture7F9F44
.incbin "textures/raw/7F9F44.i4"

.align 2, 0x00
glabel gTexture7F9FC4
.incbin "textures/raw/7F9FC4.i4"

.align 2, 0x00
glabel font_apostrophe
.incbin "textures/raw/font_apostrophe.i4"

.align 2, 0x00
glabel gTexture7FA0C4
.incbin "textures/raw/7FA0C4.i4"

.align 2, 0x00
glabel gTexture7FA194
.incbin "textures/raw/7FA194.i4"

.align 2, 0x00
glabel gTexture7FA264
.incbin "textures/raw/7FA264.i4"

.align 2, 0x00
glabel font_comma
.incbin "textures/raw/font_comma.i4"
